"""Adoption plan generation for the /TheMasterplan executor (read-only).

``plan-adopt`` inspects the project and the package manifest and produces a
machine-readable plan describing every file operation (add / modify /
generate / keep), ownership class, source hashes and stop conditions. It
never writes project files.
"""

from __future__ import annotations

from pathlib import Path

from .manifest import ManifestError, select_files
from .source import DEFAULT_REPOSITORY, Source, package_manifest
from .util import TheMasterplanError, safe_join, sha256_of_block, sha256_of_file

MANAGED_BLOCK_TEMPLATE = "distribution/templates/agents-managed-block.md"
CONSUMER_WORKFLOW_TEMPLATE = "distribution/templates/consumer-workflow.yml"
PROJECT_CHECK_TEMPLATE = "distribution/templates/project-check-placeholder.sh"


class PlanningError(TheMasterplanError):
    """Raised when a plan cannot be generated for a clear reason."""


def _package_hash(package_root: Path, relative: str) -> str | None:
    target = safe_join(package_root, relative)
    if not target.is_file():
        return None
    return sha256_of_file(target)


def _safe_exists(project_root: Path, relative: str) -> bool:
    """Path-safe existence check; unsafe paths count as not existing."""
    try:
        return safe_join(project_root, relative).is_file()
    except TheMasterplanError:
        return False


def _observed_hash(project_root: Path, destination: str, ownership: str) -> str | None:
    """Hash of an existing managed target at planning time (block hash for
    managed-block, whole-file hash otherwise). None when not readable."""
    try:
        target = safe_join(project_root, destination)
    except TheMasterplanError:
        return None
    if not target.is_file():
        return None
    if ownership == "managed-block":
        return sha256_of_block(target)
    return sha256_of_file(target)


def _classify_existing(project_root: Path, destination: str, package_root: Path, entry: dict) -> str:
    """Classify an existing destination: UNCHANGED / CONFLICT / LOCAL_ONLY."""
    try:
        target = safe_join(project_root, destination)
    except TheMasterplanError:
        return "CONFLICT"
    if not target.is_file():
        return "ADD"
    if entry["ownership"] == "managed-replace":
        pkg_hash = _package_hash(package_root, entry["source"])
        if pkg_hash is not None and sha256_of_file(target) == pkg_hash:
            return "UNCHANGED"
        return "CONFLICT"
    if entry["ownership"] == "managed-block":
        return "BLOCK_PRESENT" if _has_block_markers(target) else "BLOCK_MISSING"
    if entry["ownership"] == "generated-if-missing":
        return "EXISTS_KEEP"
    return "PROJECT_OWNED"


def _has_block_markers(path: Path) -> bool:
    text = path.read_text(encoding="utf-8", errors="replace")
    return "<!-- THEMASTERPLAN:BEGIN MANAGED -->" in text and "<!-- THEMASTERPLAN:END MANAGED -->" in text


def plan_adopt(
    project_root: Path,
    source: Source,
    *,
    profile: str,
    validation_path: str,
    default_branch: str = "main",
    validation_path_exists: bool = False,
) -> dict:
    """Generate the adoption plan for a project.

    `source` is the resolver-verified identity (repository/version/commit/
    package_root); the plan records exactly that identity. Returns a plan
    dict with source / selection / managed_files / files / notes /
    stop_conditions.
    """
    package_root = source.package_root
    manifest = package_manifest(package_root)
    # The validation entrypoint and the consumer workflow are generated by
    # the plan's generated-if-missing section against the selected
    # validation_path; manifest entries for them are filtered out here so a
    # custom validation path never also installs a default scripts/check.sh.
    entries = [
        e
        for e in select_files(manifest, profile)
        if e["destination"] not in (".github/workflows/check.yml", "scripts/check.sh")
    ]
    if not entries:
        raise PlanningError("no files selected by manifest for profile")

    # Source identity comes from the resolver only; the manifest version and
    # repository must agree with the resolver's Source (the resolver already
    # validated them, this is a defense-in-depth assertion).
    manifest_version = manifest["distribution_version"]
    manifest_repository = manifest.get("source_repository", DEFAULT_REPOSITORY)
    if source.version != manifest_version:
        raise PlanningError(
            f"source version mismatch: resolver {source.version}, manifest {manifest_version}"
        )
    if source.repository != manifest_repository:
        raise PlanningError(
            f"source repository mismatch: resolver {source.repository}, manifest {manifest_repository}"
        )

    operations: list[dict] = []
    for entry in entries:
        dest = entry["destination"]
        classification = _classify_existing(project_root, dest, package_root, entry)
        op = {
            "source": entry["source"],
            "destination": dest,
            "ownership": entry["ownership"],
            "required": entry.get("required", False),
            "classification": classification,
        }
        if classification in ("ADD", "UNCHANGED", "CONFLICT", "BLOCK_PRESENT", "BLOCK_MISSING"):
            source_hash = _package_hash(package_root, entry["source"])
            if source_hash is None:
                raise PlanningError(f"package source file missing: {entry['source']}")
            op["source_sha256"] = source_hash
        if classification in ("UNCHANGED", "EXISTS_KEEP", "BLOCK_PRESENT", "PROJECT_OWNED"):
            # Record the observed hash of existing managed targets so apply
            # can refuse when the target changed after planning.
            op["observed_sha256"] = _observed_hash(project_root, dest, entry["ownership"])
        operations.append(op)

    # generated-if-missing project files (skip destinations already in manifest).
    generated: list[dict] = []
    existing_dests = {op["destination"] for op in operations}
    for dest, template in (
        (validation_path, PROJECT_CHECK_TEMPLATE),
        (".github/workflows/check.yml", CONSUMER_WORKFLOW_TEMPLATE),
    ):
        if dest in existing_dests or any(g["destination"] == dest for g in generated):
            continue
        exists = _safe_exists(project_root, dest)
        generated.append(
            {
                "source": template,
                "destination": dest,
                "ownership": "generated-if-missing",
                "required": dest == validation_path,
                "classification": "EXISTS_KEEP" if exists else "ADD",
                "source_sha256": _package_hash(package_root, template),
                "observed_sha256": _observed_hash(project_root, dest, "generated-if-missing") if exists else None,
                "render": dest == ".github/workflows/check.yml",
            }
        )

    # Validation path must be resolvable (exists now, or provided by plan).
    if not validation_path_exists and not _safe_exists(project_root, validation_path):
        available_validation = [
            op for op in operations + generated if op["destination"] == validation_path
        ]
        if not available_validation:
            raise PlanningError(f"validation path not provided by manifest templates: {validation_path}")

    required_missing = [
        op["destination"]
        for op in operations + generated
        if op["required"] and op["classification"] in ("CONFLICT", "BLOCK_MISSING")
    ]
    stop_conditions = []
    if required_missing:
        stop_conditions.append(f"required files not installable: {', '.join(required_missing)}")
    conflicts = [op["destination"] for op in operations if op["classification"] == "CONFLICT"]
    if conflicts:
        stop_conditions.append(f"conflicting managed files: {', '.join(conflicts)}")

    plan = {
        "schema_version": 1,
        "plan_type": "adopt",
        "source": source.as_dict(),
        "selection": {
            "profile": profile,
            "validation_path": validation_path,
            "default_branch": default_branch,
        },
        "files": operations + generated,
        "notes": [
            "AGENTS.md: only the TheMasterplan managed block is written; project content outside the block is preserved.",
            "Pull request template is not auto-generated in PR A; checked by the Skill layer.",
        ],
        "stop_conditions": stop_conditions,
    }
    return plan
